name: Build V2X-Hub Docker Image
on:
  push:
    branches:
      - multiarch-test

jobs:
  build-amd64:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Show r63 folder
        run: |
          echo "=== Debugging r63 for AMD64 job ==="
          ls -R src/tmx/Asn_J2735/src/r63 || true

      - name: Set up Docker Buildx (no ephemeral)
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true
          ephemeral: false
          driver-opts: |
            image=moby/buildkit:rootless
            network=host

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build amd64
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: saikrishnabairamoni/v2xhub:amd64-latest


  build-arm64:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Show r63 folder
        run: |
          echo "=== Debugging r63 for ARM64 job ==="
          ls -R src/tmx/Asn_J2735/src/r63 || true

      - name: Set up Docker Buildx (no ephemeral)
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true
          ephemeral: false
          driver-opts: |
            image=moby/buildkit:rootless
            network=host

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build arm64
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          tags: saikrishnabairamoni/v2xhub:arm64-latest


  manifest:
    runs-on: ubuntu-22.04
    needs: [build-amd64, build-arm64]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create saikrishnabairamoni/v2xhub:multiarch-test \
            saikrishnabairamoni/v2xhub:amd64-latest \
            saikrishnabairamoni/v2xhub:arm64-latest

          docker manifest push saikrishnabairamoni/v2xhub:multiarch-test
